### ISSUE TITLE
Kite completions not compatible with other completions providers

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#117]
From user feedback:

> I wished if kite took too long to generate suggestions ( like 300 ms max), then it would fall back to the vim's default CTRL-n suggestions. I was not able to find a way to fall-back to the vim's default CTRL-n behavior and kite's latency was too long too many times.

We should investigate if it's possible for Kite to coexist with other popular completions plugins

**Comment by cliffxuan** [comment]
I cannot do `<C-N>` completion with default options. If I set `let g:kite_auto_complete=0`, CTRL-n work, but I like the default behaviour and don't want to do `<C-X><C-U>`.

Is this a bug?

**Comment by airblade** [comment]
> I like the default behaviour

Whose default behaviour?  I'm not quite sure what you mean here.

**Comment by cliffxuan** [comment]
@airblade thanks for the reply. sorry for not being clear.

I mean the default behaviour of Kite vim-plugin, where completions will show up automatically as you type.

I rely on `Ctrl+N` and `Ctrl+P` for word completion very heavily, which doesn't work with Kite vim-plugin.

**Comment by airblade** [comment]
@cliffxuan This is fixed in ab5a048 (I hope!).  Please could you try it and let me know if it works for you?

**Comment by cliffxuan** [comment]
@airblade sure. will try it out and let you know.

**Comment by cliffxuan** [comment]
@airblade it's working now. thanks for the fix.

**Comment by airblade** [comment]
@cliffxuan That's great to hear.  Thanks for confirming.

**Comment by airblade** [comment]
@its-dhung With ab5a048 it is possible for Kite to coexist with other completion methods.

I don't think automatic fallback, e.g. from Kite's suggestions to keyword suggestions, is a good idea – that's not the vim way.  If a user wants that behaviour, I recommend [mucomplete](https://github.com/lifepillar/vim-mucomplete) into which they can plug Kite's completions (as used-defined completions, i.e. via `completefunc`).

Do you have any objections to my closing this issue now?

**Comment by jansorg** [comment]
@its-dhung Closing this now. Feel free to reopen when needed.
