### ISSUE TITLE
start kited at startup

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#136]
Autostart kited at startup of the plugin.

- if necessary add a new setting to disable the automatic startup, default to false, i.e. to an automatic start of kited
- if setting "start kited at startup" is enabled:
    - detect if kited is running at startup
         - if not running: detect if kited is installed
            - if installed: **launch kited**

Locating and launching kite:
https://kite.quip.com/rVcJA1bIqZny/Kite-Status-Spec#QcWACAD7xTp

**Comment by airblade** [comment]
Done in #144.
