### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#151]
@airblade Please add a note with the settings/values you need to implement support for Kite on Linux.

**Comment by airblade** [comment]
The shell commands to:

- detect whether and where Kite is installed;
- detect whether Kite is running;
  - currently using `ps -axco command` and grepping for `^Kite$`
- launch Kite.

**Comment by jansorg** [comment]
This is how kite will be installed on Linux:
- binary name `kited`, default location is `/usr/bin/kited`. This is a script which launches a `kited` binary from a subdirectory of `/opt/kited/`
- Detection: The ps command and grepping for `^kite$` should be fine
- Launching: launch `kited` from `$PATH`

**Comment by airblade** [comment]
Done in #152.
