### ISSUE TITLE
Completions snippets being automatically inserted into buffer

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#153]
From user feedback:

> Using MacVim 8.1, Kite is randomly typing in lots of text from the help docs directly into my input buffer, requiring me to stop using it.

**Comment by airblade** [comment]
The behaviour of the completions is controlled by the `completeopt` option.  The plugin sets `completeopt` to work well with Kite's autocompletion if and only if the user hasn't already configured it.

The [readme explains this in detail](https://github.com/kiteco/vim-plugin#completions).

The first step is to ask the user to do `:verbose echo &completeopt`.  This will print out the option value and also say what set it to that value.

Does the user want Kite to autocomplete?  If not, they should `:let g:kite_auto_complete=0`.  If they do, but don't want Vim to insert the first option automatically, they should `:set completeopt+=noinsert`.  It's all explained in the readme and Vim's help (`:help completeopt`).

**Comment by airblade** [comment]
FYI I got the command slightly wrong above: it should be `:verbose set completeopt?`.

**Comment by its-dhung** [comment]
Hi @airblade, the user reports that both these behaviors (auto-inserting text and docs split window showing) still occur even after removing `preview` and `noinsert` from `completeopt`. Is there anything else we can try to debug?

**Comment by khchen428** [comment]
Thanks for linking to the readme! I did want the Kite autocomplete but not the automatic insert as well as auto-closing the preview, so that did the trick.  It would be great if the readme were linked from the Kite Copilot since I didn't know about this repo.

**Comment by its-dhung** [comment]
Thanks for clarifying @khchen428. Can we close this issue now since you've resolved your issue?

I'll create a separate issue to track your suggestion on how to surface these helpful docs better.

**Comment by khchen428** [comment]
Perfect, thanks!
