### ISSUE TITLE
Make README more discoverable

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#154]
The docs included in the `README.md` are very helpful. We should figure out a way to surface it through the product better, whether its through this plugin or through the Copilot.

**Comment by airblade** [comment]
The "Vim way" is to write docs in Vim's help format so they are picked up and accessible from within Vim.  Then a user could do `:help kite` or, say, `:help kite-completion`.

It wouldn't take long to copy and adapt the readme for this.

**Comment by its-dhung** [comment]
That sounds great. Before we do this, let me think a little bit on what other information we should include in the help docs.

**Comment by metalogical** [comment]
I think we can go ahead and do this, and if there are any changes to be made to the help document or README, we can do that iteratively.
