### ISSUE TITLE
Slow startuptime when checking os with system(uname)

### ISSUE THREAD

**Issue by yochem** [kiteco/vim-plugin#156]
I didn't find a way to do this, but is it possible to only load kite when opening a python file? I try to keep nvim startuptime as low as possible, and kite adding almost 100 ms is not really helping with that.

Looking forward to hear from you!

**Comment by airblade** [comment]
Please could you post a profile so I can identify exactly which parts are slow?

Add these two lines to your vimrc, ensuring you put them above any package or path manager such as pathogen.

```viml
profile start profile.log
profile! file */kite/*
```

Now launch Vim and do whatever makes it slow. When you quit Vim it will write the log file in the current directory.

Please post the log file in a gist and send me a link.

**Comment by yochem** [comment]
Added the two lines above everything in my `.vimrc`. [Here's](https://gist.github.com/yochem/84173f4ea73173819b477d1fbdb4cedc) the gist. While using nvim it's not slow, but the startuptime is slower than normal.

**Comment by airblade** [comment]
Thanks for the profile.

The only thing I can see that takes more than 1ms is this (line 81):

```
    1   0.048370   0.000069   let uname = substitute(system('uname'), '\n', '', '')  " Darwin or Linux
```

But that's only 48ms.  I can't see from the profile why the startup time would be slow.

Please could you try:

- replacing the line quoted above with `let uname = 'Darwin'` (or Linux, whichever is appropriate) and see if that removes the slowness?
- Executing `:KiteDisableAutoStart`, then quitting and launching nvim.

**Comment by yochem** [comment]
These are the outputs of `nvim --startuptime nvim.log`:

![image](https://user-images.githubusercontent.com/23235841/56650788-0d864700-6688-11e9-846f-25183a873f68.png)

`nvim.log` is with `let uname = 'Darwin'` and `nvim2.log` is with `let uname = substitute(system('uname'), '\n', '', '')`. The difference is significant. So I think you're right, it's in the system call.

**Comment by airblade** [comment]
I think when Vim executes `system('uname')` it basically does `bash -c 'uname'` (or whatever your shell is).  This suggests that your shell startup is a bit slow.  Do you have a way to profile that?

**Comment by jansorg** [comment]
@airblade There's `/proc/version` on Linux, https://www.unixtutorial.org/use-proc-version-to-identify-your-linux-release . If the content contains `Linux` then you can safely assume that you're on Linux.
This might help to remove the call to `uname`.

**Comment by yochem** [comment]
Timing bash -c 'uname' gives this as result:
```bash
$ time bash -c 'uname'
Darwin

real	0m0.034s
user	0m0.013s
sys	0m0.017s
```
and using [this](https://stackoverflow.com/a/5015179/7442167) to profile bash gives [this](https://gist.github.com/yochem/0775261c813ae16c3cd513e563b4696e) result (gist). I don't think the gist is very helpful though. Maybe using Vim's OS checking is faster. We could then change
```vim
if has('win64') || has('win32') || has('win32unix')
  let s:os = 'windows'
else
  let uname = substitute(system('uname'), '\n', '', '')  " Darwin or Linux
  let s:os = uname ==? 'Darwin' ? 'macos' : 'linux'
endif
```
with:
```vim
if has('win64') || has('win32') || has('win32unix')
    let s:os = 'windows'
elseif has('macunix')
    let s:os = 'macos'
else
    let s:os = 'linux'
endif
```

**Comment by airblade** [comment]
@yochem Thanks for the gist.  I agree, it's hard to get anything actionable from it.

Unfortunately `has('macunix')` isn't a reliable guide to whether we are on macOS.  The default `/usr/bin/vim/` returns 0 to `has('macunix')` and `has('mac')`.  I don't think there's a built in way to distinguish macOS from linux; we have to execute an external command.

The puzzle is why this is slow.

**Comment by airblade** [comment]
@jansorg We would still need to execute a `system()` call, which I assume is the slow part (not `uname`).

**Comment by airblade** [comment]
@jansorg Oh, we wouldn't need to execute a `system()` call.  We could use `findfile('/proc/version')` and if it's present, we're on linux; if not, macOS.

@yochem Please could you try this patch?

```diff
diff --git i/autoload/kite/utils.vim w/autoload/kite/utils.vim
index a611c66..3a0f7a8 100644
--- i/autoload/kite/utils.vim
+++ w/autoload/kite/utils.vim
@@ -3,8 +3,7 @@
 if has('win64') || has('win32') || has('win32unix')
   let s:os = 'windows'
 else
-  let uname = substitute(system('uname'), '\n', '', '')  " Darwin or Linux
-  let s:os = uname ==? 'Darwin' ? 'macos' : 'linux'
+  let s:os = empty(findfile('/proc/version')) ? 'macos' : 'linux'
 endif

 function! kite#utils#windows()
```

**Comment by yochem** [comment]
Sure! I found that solution too, but do we know it's legit? Does every linux distro have `/proc/version`?

**Comment by airblade** [comment]
> is it possible to only load kite when opening a python file?

Yes, we can do this if we can't find a way to speed up detection of macOS vs linux.

**Comment by yochem** [comment]
Speed improvement with nvim:
```bash
$ nvim --startuptime old.log
$ cat old.log | grep kite
116.585  042.795  042.795: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/utils.vim
117.168  000.271  000.271: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/autoload/kite.vim
117.782  044.429  001.335: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/plugin/kite.vim
```
with `let s:os = empty(findfile('/proc/version')) ? 'macos' : 'linux'`:
```bash
$ nvim --startuptime new.log
$ cat new.log | grep kite
216.054  001.232  001.232: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/autoload/kite/utils.vim
219.305  002.942  002.942: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/autoload/kite.vim
223.481  011.949  007.719: sourcing /Users/Yochem/.config/nvim/pack/kite/start/vim-plugin/plugin/kite.vim
```
So by checking for /proc/version sourcing the kite plugin is around 4x faster on my machine.

**Comment by airblade** [comment]
It might be more general to check for `/proc` instead of `/proc/version`.

According to the [Wikipedia page on procfs](https://en.wikipedia.org/wiki/Procfs), most Unix-like OSs use procfs but OpenBSD does not.  I'm not sure how many OpenBSD users of the Vim plugin there are.

Alternatively we could look for the presence of `launchd` which I believe is only found on macOS.

**Comment by yochem** [comment]
Would you check for the system call launchd? Wouldn't that be just as slow as running `uname`? The slowness didn't come from `uname`, but from spawning a bash session. Or would you check for `/System/Library/LaunchDaemons`?

**Comment by airblade** [comment]
`/sbin/launchd` is a file so you can check for it with `findfile()` as above.  Same with `/System/Library/LanchDaemons`.

I think it's more reliable to look for a macOS-specific thing than a thing which is found on all linux distros.

**Comment by airblade** [comment]
@yochem Have you figured out why your shell is slow to launch?

**Comment by yochem** [comment]
Will change it to `/sbin/launchd` in #162. I think but my shell is slow because it loads a bunch of autocompletion files (`[ -d /usr/local/etc/bash_completion.d ] && . /usr/local/etc/bash_completion.d/*`).

**Comment by yochem** [comment]
By the way, off topic question: is it possible to move `~/.kite~ to a XDG standard location?

**Comment by jansorg** [comment]
@yochem Good point about the standard location. For now you can use a symlink to keep kite's data in a standard location. I'll open an issue with the Kite team to see if it's possible to change the default location on Linux.

**Comment by yochem** [comment]
@jansorg Thanks 🙌 . will it be possible on MacOS, too? I know it isn't the standard but I'd still like a cleaner `$HOME`.

**Comment by jansorg** [comment]
@yochem For now I only had Linux on my mind for this. Which location would you prefer on macOS instead of `$HOME/.kite`?

**Comment by airblade** [comment]
@yochem FYI #165 speeds up startup even more.

**Comment by yochem** [comment]
@jansorg I would love the XDG standard on MacOS, even though Apple recommends [other paths](https://stackoverflow.com/a/5084892/7442167). I personally like the compatibility between *nix systems.

**Comment by jansorg** [comment]
@yochem Thanks for the input on macOS. 
~/.kite is used for settings and a log file. We'll try to make this to $XDG_CONFIG_HOME/kited but can't promise at this time.
I don't expect that locations for macOS will change anytime soon.

**Comment by airblade** [comment]
The Kite plugin doesn't increase Vim's startup time now, which was the original issue, so I'm closing this.

@yochem Thanks for reporting the problem.
