### ISSUE TITLE
Error opening a file in an ignored directory

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#159]
When opening a file in an ignored directory e.g. anything in `~/Library` on macOS, the Vim plugin shows this error:

```
Error detected while processing function kite#bufenter[8]..kite#status#status[28]..kite#client#status[7]..kite#status#ha
ndler:
line   21:
E121: Undefined variable: msg
Press ENTER or type command to continue
Error detected while processing function kite#status#status[28]..kite#client#status[7]..kite#status#handler:
line   21:
E121: Undefined variable: msg
Press ENTER or type command to continue
```

**Comment by airblade** [comment]
From the code this error can only occur if the status from kited is none of `ready`, `syncing`, `indexing`.  I thought these were the only possible values – are there others?  What should the user-visible status be for any other value?

**Comment by jansorg** [comment]
If Kite returns another value, e.g. an empty value, then hide the status bar element in the vim plugin.

**Comment by airblade** [comment]
@jansorg Can this be closed now?

**Comment by its-dhung** [comment]
Looks like this can be closed. I'll let the user know and ask him to tell us if he experiences this again.
