### ISSUE TITLE
Make popular patterns configurable

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#164]
We should add an option which controls whether or not popular patterns (a.k.a. "How Others Used This") are displayed when the function signature UI is shown. This option should default to false. We may need some affordance in the function signature UI to let the user know that there are examples to be shown.

See kiteco/kiteco#7866 for motivation.

**Comment by airblade** [comment]
Currently popular patterns are only shown to [users on the Pro plan](https://github.com/kiteco/vim-plugin/blob/8d1306c0b46296f89abefbb035a97a7fb0d0efcc/autoload/kite/signature.vim#L145).

**Comment by jansorg** [comment]
@airblade You can safely drop the check for pro plans. With Kite Local there's always a pro plan and this isn't going to change for now.

**Comment by airblade** [comment]
Done in #167.
