### ISSUE TITLE
Error getting status in Neovim

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#170]
Some user feedback received recently:

> 1) using the statusbar in vim (I use nvim so this might just be something that isnt supported) just copied the plubin folder from ~/.vim into ~/.config/nvim/bundle and im seeing this error when nvim goes to update my statusline
>  
> ```
> Error detected while processing function kite#status#status[28]..kite#client#status[7]..kite#status#handler:
> line 21:
> E121: Undefined variable: msg
> E15: Invalid expression: msg !=# getbufvar(a:buffer, 'kite_status')
> ```

**Comment by tarakju** [comment]
This was on linux, if that's relevant.

**Comment by airblade** [comment]
This sounds like #159 which was fixed in #166 (08e072f6).

**Comment by airblade** [comment]
The user can do `:echo kite#utils#plugin_version()` to see what version of the plugin they have.  This fix is in `1.0.28`.

**Comment by its-dhung** [comment]
Yes, this may be the same as #159. I'll ask the user where he was opening Vim.

**Comment by jansorg** [comment]
Closing as #159 is fixed.
