### ISSUE TITLE
Vim plugin hangs on large files

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#172]
From user feedback:

> Plugin fails to process big files. Big mean more than 4k lines long. In neovim it leads to annoying interrupting of any movement.

I believe we should be ignoring files >1MB. If we're already doing this, we may need to consider decreasing the max file size it if the files within this range are causing the plugin to lag.

**Comment by airblade** [comment]
The plugin ignores files >1MB for events, hover docs, and status.  But looking at it now, it won't be ignoring big files for completions.

This is an easy change.  Once it's in master you could ask the user to upgrade and, if the problem doesn't go away, get a profile.

**Comment by airblade** [comment]
@its-dhung Please can you ask the user to upgrade the plugin and try again?  If there is still a problem, it would be great if they could run a vim profile and post the results somewhere, e.g. as a gist.
