### ISSUE TITLE
Completions menu does not persist

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#178]
Linux user reported that completions menu does not persist

> Configuration: I'm using nvim with coc.nvim, with coc-python extension installed and python.jediEnabled config as false
> 
> Bug:
> As I type, the auto completion box briefly appears to just as fast disappear as I'm typing. If I stop typing, it closes instead of persisting
> 
> Expected behavior:
> As I type, the auto completion box should update, if I stop typing the auto completion box should persist with suggestions so it's possible to navigate

**Comment by airblade** [comment]
I can't reproduce this.  This is what I did.

- Check neovim version: 0.3.4.
- Check node is installed.
- Install [coc.nvim](https://github.com/neoclide/coc.nvim) and Kite as my only plugins, using my plugin manager.
- In neovim:
    `:call coc#util#install()`
    `:CocInstall coc-python`
    `:CocInstall coc-json`
    `:CocConfig` and then `"python.jediEnabled": false`
- Ensure Kite autocompletion is on (`:echo g:kite_auto_complete` is `1`).
- Edit a python file and start typing.

When I type I see the auto completion box; when I stop typing it remains in place.

Does the user want to use Kite for the autocompletions and coc.nvim for non-autocompletion things such as navigation?

I have never used coc.nvim myself so I don't know how to turn off its autocompletions.

Could the user link to his `init.vim` neovim configuration?

**Comment by gugahoa** [comment]
Hello everyone!
I'm the user in question who reported the bug, here's my complete `init.vim` and `coc-settings.json` (`coc-settings.json` can be accessed via `:CocConfig`): https://gist.github.com/gugahoa/8022e0bc6350b671af9f149deb92a54d

**Comment by gugahoa** [comment]
From what I can see, Kite is trying to override currently open auto complete box, so at each keystroke coc.nvim's auto completion suggestions and Kite's own conflict with each other

**Comment by airblade** [comment]
@gugahoa Which completions do you want – Kite's or coc.nvim's?

**Comment by gugahoa** [comment]
Both, actually

**Comment by airblade** [comment]
Mixed together in the same popup?  I don't see how that's possible.

**Comment by gugahoa** [comment]
Hmmm, then it's a bit hard to decide. Does Kite autocompletion includes what the LanguageServer could achieve and more? If so, I would prefer Kite.

**Comment by airblade** [comment]
@its-dhung You can answer that better than I can :)

**Comment by its-dhung** [comment]
@gugahoa if you're using Jedi as the LSP backend, Kite should provide a significant improvement because our type inference engine is able to resolve more types, and therefore is able to provide more completions (will try to dig up numbers for this). We constantly work on improving our type inference, so you should expect to see Kite's completions improve over time. We're also working on a couple of enhancements to our completions UX which I think is a step function improvement over what other completions plugins can provide.

One thing Kite does not currently do is provide completions for keywords seen in the current buffer, though this in theory is a lot easier to implement than semantic completions. I'm curious if you rely on keyword completions as a core part the completions experience?

**Comment by gugahoa** [comment]
I use it quite heavily but I can give a chance to Kite only auto completion and give feedback if my experience changed too much, if you would like

**Comment by its-dhung** [comment]
That would be great, we always enjoy getting honest feedback from users! I'll email you some details on how you can submit feedback so that we can act on it.

**Comment by airblade** [comment]
We hope to have a way to integrate Kite's completions with COC soon.
