### ISSUE TITLE
Strange UI in NeoVim on Windows

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#184]
This is how Neovim Qt 0.3.5 on Windows is displaying the completions:
![Screenshot_20190527_143635](https://user-images.githubusercontent.com/11473063/58420147-e5c23e80-808c-11e9-9de8-3e1d1156b7f5.png)

_To be ignored:_
This is how the signature panel is displayed:
![Screenshot_20190527_143801](https://user-images.githubusercontent.com/11473063/58420252-14d8b000-808d-11e9-8170-f16aeaa113ff.png)

Is there a way to improve the rendering somehow?

**Comment by airblade** [comment]
I don't know what's going on in the first screenshot.  That's really odd.

In the second, the height of the popup window is limited to 10 (see #121) although only 4 lines are used here.  The width is set to 50 characters (see #35, though it doesn't say why).  Would you like to increase the width?  We could, for example, calculate the width of the window, and the current column number, and try to use up most of the available space to the right.

**Comment by jansorg** [comment]
In the first screenshot the documentation seems to be rendered inside of the popup.
I'd like to avoid to change things just because of NeoVim as this could make things worse for Vim or gVim.
Let's keep this open for now and test a bit more with NeoVim to see what might be going on here.

**Comment by airblade** [comment]
@jansorg Neovim does the right thing on macOS, so I'm confident I'm using vim/neovim's completion mechanism correctly.

<img width="847" alt="Screenshot 2019-05-29 at 4 09 35 pm" src="https://user-images.githubusercontent.com/7265/58568489-46d44880-822c-11e9-8a37-9aa966ca2edc.png">

I'll see if I can find any error reports about Windows and QT.

**Comment by airblade** [comment]
I can't find anything on neovim's repo about this.

Does adding `GuiPopupmenu 0` to `ginit.vim` help?  [Source](https://jdhao.github.io/2019/01/17/nvim_qt_settings_on_windows/#how-to-turn-off-gui-completion-menu)

**Comment by jansorg** [comment]
@airblade The `GuiPopupmenu` options improves the completion menu for NeoVim. This also fixed the rendering of the parameters popup (i.e. the 2nd screenshot). 
Do you mind to add a quick note to the Readme file which recommends this setting for users of Neovim?

**Comment by airblade** [comment]
Done in #187.
