### ISSUE TITLE
Typed characters lost with Neovim

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#190]
Tested with:
- Windows 10
- NeoVim 0.3.7 (win64), available at https://github.com/neovim/neovim/releases/tag/v0.3.7
- current master of `vim-plugin`
- This doesn't seem to happen with 0.3.7 on Linux

1. Double click on the console application `Neovim\bin\nvim.exe`
1. Open a python file
2. Type `import json` in insert mode
3. Press enter and enter `j`
4. A popup menu appear, showing `json     module` here
4. enter `s`
5. nvim now changes the line to `s ` with the caret after the whitespace. The popup is still showing `json`.

![Screenshot_20190619_152903](https://user-images.githubusercontent.com/11473063/59769720-fd18d400-92a6-11e9-9732-b1f0cbff7b7a.png)

**Comment by jansorg** [comment]
@airblade  Tested again on Windows 10 with the same version of vim. I'm not able to reproduce this anymore. I'm not sure why. Perhaps this was fixed by the more recent commits to master.
I'm closing this for now. Let's re-investigate when we're seeing this again.

**Comment by airblade** [comment]
@jansorg That's a relief ;)
