### ISSUE TITLE
Kite not working in paste mode

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#191]
A user mentioned that Kite didn't show completions after running `set paste`. Does it make sense for Kite to work in paste mode?

**Comment by airblade** [comment]
No, it doesn't make sense for Kite to work in paste mode.  Vim's paste setting is designed to be toggled on just before you paste something and then off afterwards (which is a clunky workflow, but that's how it is).  People often configure their Vim to interact with their terminal's bracketed paste mode so the paste setting is toggled on and off automatically.

The reason completions aren't shown after `set paste` is that paste mode disables insert mode mappings, among other things, and the plugin uses insert mode mappings for insert mode completion.

**Comment by its-dhung** [comment]
Thanks for the clarification. Perhaps Kite's status indicator should let the user know it's inactive when it detects that the editor is in paste mode? Not sure how many users would be confused by this situation.
