### ISSUE TITLE
Kite plugin slow when using iTerm2

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#192]
From https://twitter.com/RhetTurnbull/status/1145687664521142272:

> I want to love Kite but VIM plugin on Mac + iTerm2 just doesn't work. Slows keystrokes down and inserts random letters as I type.

**Comment by airblade** [comment]
I wonder if the random letters are the as-you-type automatic completion failing to keep up with the user's typing.  The user could try `let g:kite_auto_complete=0`.

It would also help to know what `:echo kite#utils#plugin_version()` prints, and the Vim version.

An [asciicast](https://asciinema.org) would help show the nature of the problem.

**Comment by airblade** [comment]
We've made a number of changes to avoid garbage being inserted into the buffer, and to keep the UI fast.  I'm going to close this now; we can always open a new issue if this comes up again.
