### ISSUE TITLE
Support new status 'noIndex'

### ISSUE THREAD

**Issue by jansorg** [kiteco/vim-plugin#194]
Kite will soon support a new file status `noIndex`. It is returned by `/clientapi/status` for files which live outside of the indexed directories (i.e. usually $HOME).

Needed changes:
- Display `Kite: ready (unindexed)` for file status `noIndex`
- Drop support of the `ignored` state (and `syncing`, if still in use)

**Comment by airblade** [comment]
Done in #195.
