### ISSUE TITLE
Error while processing function kite#snippet#complete_done

### ISSUE THREAD

**Issue by jackson211** [kiteco/vim-plugin#197]
I reinstalled kite and this error happened  
OS: macOS 10.14.6
system default vim 8
`Error detected while processing function kite#snippet#complete_done:
line    3:
E716: Key not present in Dictionary: user_data)
Press ENTER or type command to continue
`

**Comment by metalogical** [comment]
do you use Deoplete or other completions plugins?

**Comment by jackson211** [comment]
> do you use Deoplete or other completions plugins?

I just found out it was black Formatter, uninstalled black and it fixed.

**Comment by metalogical** [comment]
Interesting, thanks for the note.

We'll add that to our list of plugins that (currently) do not interact well with Kite.
