### ISSUE TITLE
plugin incompatibility: "Key not present in Dictionary: user_data)"

### ISSUE THREAD

**Issue by metalogical** [kiteco/vim-plugin#199]
```
Error detected while processing function kite#snippet#complete_done: line 3: E716: Key not present in Dictionary: user_data) Press ENTER or type command to continue
```

We've had a couple user reports of the error above. #197 confirmed that Black (https://github.com/psf/black/blob/master/plugin/black.vim) was the culprit, but there may be other causes as well.

We should probably try to fix this, as opposed to disabling it (#183) since Black is not a completions plugin, and users may legitimately want to run both Kite and Black.

**Comment by airblade** [comment]
At a high level Black replaces the buffer's contents with new contents.

It has to be triggered somehow.  The readme suggests:

```viml
autocmd BufWritePre *.py execute ':Black'
```

It would be good to know if the users running into problems were triggering Black this way or another way.

At first glance I don't see how Black and Kite would interfere with each other.  The error message suggests that our plugin is responding to a non-Kite completion – but as you say Black is not a completion plugin.

**Comment by airblade** [comment]
I can't reproduce the error.

**Comment by metalogical** [comment]
Thanks for looking into it. I'll update with more info if I get it from our users.

**Comment by paiforsyth** [comment]
I am getting this error with an empty .vimrc and .vim directory containing only the kite plugin

**Comment by lumingdong** [comment]
> I am getting this error with an empty .vimrc and .vim directory containing only the kite plugin

I also encountered the same problem. @airblade
