### ISSUE TITLE
macOS Sierra and KiteSidebar Issues

### ISSUE THREAD

**Issue by hellosputnik** [kiteco/vim-plugin#2]
`which vim` returns `/usr/local/bin/vim` which is Vim 8.0, but there is another installation of Vim at `/usr/bin/vim` which is Vim 7.4.

I initially thought that this may be the problem, but I tried editing a Python file with both versions and there was no response from KiteSidebar regardless of the version.

[client.log.txt](https://github.com/kiteco/vim-plugin/files/877060/client.log.txt)

**Comment by alexflint** [comment]
Based on that log file it appears that you haven't whitelisted the directory that you're working in. Adding a new whitelisted directory should solve your problem: http://help.kite.com/article/12-how-can-i-see-which-directories-kite-is-indexing.

Feel free to re-open if the issue persists.

**Comment by hellosputnik** [comment]
Thanks, Alex. That solved the issue.

Please correct me if I am misunderstanding, but I must upload my directories (or information about my directories) in order for Kite to properly function unless I purchase Kite Pro?

Is there a privacy policy that I can read?
