### ISSUE TITLE
plugin incompatibility: "Key not present in Dictionary: user_data)"

### ISSUE THREAD

**Issue by lumingdong** [kiteco/vim-plugin#203]
I get this error when i type the enter try to choose a completion code.
[Here is a gif!](https://postimg.cc/LY3WvTVJ)
Some infomation:
MacOS + iterm2 + Vim8 + Kite-vim-plugin(1.0.39, only the kite plugin)

**Comment by metalogical** [comment]
closing in favor of the original #199

**Comment by airblade** [comment]
@lumingdong Thank you for the gif!
