### ISSUE TITLE
Vim CoPilot Lag/Unresponsiveness

### ISSUE THREAD

**Issue by techwithtim** [kiteco/vim-plugin#210]
When using Vim with the Kite stand alone copilot window there is severe lag and it very rarely works. When using it with sublime text, atom or pycharm on the same machine there are no problems.

**Comment by airblade** [comment]
Does Vim's responsiveness improve when you close the copilot window?

**Comment by techwithtim** [comment]
Vim is very responsive, just the Kite window itself that shows the docs is not. 
Note: This is on windows 10.

**Comment by airblade** [comment]
@techwithtim What does this give?  `:echo &updatetime`

**Comment by techwithtim** [comment]
Output is "4000"

**Comment by airblade** [comment]
Thank you.  This should fix the lag: `:set updatetime=100`; you can add this to your vimrc.

In the meantime I'll look for a solution which doesn't require you to change your `updatetime`.

**Comment by airblade** [comment]
Kite should already have set your `updatetime` for you (bf399bfa23).

I wonder why yours remained `4000`.

**Comment by airblade** [comment]
Please could you tell me what this gives? `:verbose echo &updatetime`.

**Comment by airblade** [comment]
I'm closing this because it's over a year old and both the plugin and the Kite window have changed a lot since this issue was opened.  If you're still experiencing a lag, please let me know and we'll open a new issue.  Thanks!
