### ISSUE TITLE
Kite Icon Does not Appear on Vim

### ISSUE THREAD

**Issue by techwithtim** [kiteco/vim-plugin#211]
OS: Windows 10

When using Vim with kite the small kite icons that are supposed to show before the suggestions appear as "á".

![vim issue](https://user-images.githubusercontent.com/35348871/65598514-9e2fbe80-df69-11e9-8c3e-eb55f291e383.PNG)

**Comment by airblade** [comment]
This is similar to #168 which was fixed by 809894b.  Evidently this doesn't show the Kite symbol for you:

```viml
:echo nr2char(printf('%d', '0x27E0'))
```

Maybe your font doesn't have that symbol?

This is the symbol: https://www.fileformat.info/info/unicode/char/27e0/index.htm

**Comment by jansorg** [comment]
@its-dhung On Windows, the character `⟠` seems to be missing in the default font so it's not possible to render. Seen here on Windows 10, gVim.
We have to either hide this or use another character on Windows.

**Comment by adamsmith** [comment]
`k`?

**Comment by adamsmith** [comment]
Discussed with Daniel. Let's use `[k]`. If we can't detect the specific condition of the font not having the character maybe we should revert to this on Windows? (@airblade)
