### ISSUE TITLE
Changes to completeopt

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#217]
I think we should both

1. Set `completeopt-=preview` by default.
2. Have the preview buffer open at the bottom of the window instead of the top so that it doesn't cause the currently selected line to jump around.

**Comment by airblade** [comment]
1.  I think the only reason we don't already do this is so people become aware that there is extra information available.  I imagine most people turn it off though.

2.  Vim opens the preview window during completions, not us, so the only way to achieve this is with `:set splitbelow`.  However that affects how any window will get split, not just the preview window.  A compromise would be just to do it for python buffers.

Personally I think split below is much nicer than the default of split above.

**Comment by its-dhung** [comment]
> I think the only reason we don't already do this is so people become aware that there is extra information available. I imagine most people turn it off though.

Is is possible to by default automatically close the preview window when a completion has been selected via `autocmd CompleteDone * if !pumvisible() | pclose | endif`?

> Vim opens the preview window during completions, not us, so the only way to achieve this is with :set splitbelow. However that affects how any window will get split, not just the preview window. A compromise would be just to do it for python buffers.

If we decide to keep the preview window on by default, I think we should make it split below for Python buffers.

**Comment by adamsmith** [comment]
Seems like we should have it default off if we think it's not valuable enough that most people, given the option, wouldn't keep it on. In particular because it's such a large UI. And we can rely on other ways to educate users about it, e.g. the onboarding file, and we will be doing more on the marketing team soon around user education also.

FWIW we recently got negative user feedback about this panel. (I'm not sure whether that user knew how to turn it off.)

**Comment by jansorg** [comment]
Results after discussing with Andy:
- `completeopt` is global in vim. We'll always get some side-effects if we try to treat it local
- Andy will investigate if other plugins, like Jedi, handle this somehow else which is preferable
- If there's not better way, then we'll add a flag to control the completeopts for python buffers, e.g. `kite_completeopt`. 
- `kite_completeopt` is set to a meaninful default by the Kite plugin, unless the user already modified it, e.g. in `vimrc`
- when a user enters a python buffer, then `completeopt=kite_completeopt`
- when a users leaves a python buffer, then the original value of `completeopt` is restored

This is similar to what we had before, but it has these advantages:
- we're not overriding something which is used elsewhere (i.e. `completeopt`). 
- we're hiding the preview panel in python buffers by default
- we still allow the user to control `kite_completeopt` if he/she wants to

**Comment by its-dhung** [comment]
> If the user changes completeopt in a Python buffer, e.g. adding or removing preview, should that change apply to the global completeopt when they enter a non-Python buffer?

Yes, I think the user would expect this change to apply to the global `completeopt` as well.

> Similarly, if the user changes completeopt in a non-Python buffer, e.g. adding or removing preview, should that change apply to the Python completeopt when they enter a Python buffer?

Yes, I think the user would expect this change to be global and therefore should apply to Python buffers.

In general, if the user has made a manual change to `completeopt`, we have to assume the user knows what they were doing and therefore they would expect to see the change applied globally.

**Comment by airblade** [comment]
[Jedi sets `completeopt`](https://github.com/davidhalter/jedi-vim/blob/b4b2f3ef54c02d6f8fb09cf1eb0f139d3a45bdb8/plugin/jedi.vim#L27-L46) (to `menuone,longest,preview`) if and only if the user hasn't already set `completeopt` themself.  This is done at Vim startup.  The user can also opt out of Jedi's auto configuration (which includes mappings as well as `completeopt`).

**Comment by airblade** [comment]
This is how our thinking has progressed:

- Originally we documented our recommended `completeopt` in the readme ([link](https://github.com/kiteco/vim-plugin/blob/d152469e81213b27cd1b9fdf4eb4e15842d54fd1/README.md#completions)).
- Then we configured `completeopt` if and only if the user hadn't (dfadf5f).
- Then we tried to eliminate side-effects for non-Python files (a05b65f).
- Then we always configured `completeopt` (69def8c).

Given that other popular completion plugins don't worry about the side-effects of setting `completeopt`, how about this:

- If the user has set `completeopt`:
  - assume they know what they are doing and don't change it;
  - if `completeopt` doesn't contain `menuone,noinsert` or does contain `longest`, show a warning every time completion is attempted and don't attempt the completion.
- If the user hasn't set `completeopt`, set it ourselves, once, at Vim startup.

The benefits are:

- users who don't know about `completeopt` get the best completion experience;
- users who do know about `completeopt` can set it at will, e.g. showing/hiding the preview, and their changes are not overwritten when they enter a new buffer;
- we protect against "bad" `completeopt` configurations which would break our completions.

**Comment by airblade** [comment]
> Would the warning (as outlined above) take focus or require the user's attention to remove it?

No to both.  However if the user has `showmode` on and a `cmdheight` (the height of the command line) of 1, which are the defaults, the warning won't be visible because it will be hidden by Vim showing the mode: `-- INSERT --`.

**Comment by jansorg** [comment]
@its-dhung cc @metalogical  Does the plan outlined above sound okay to you?

**Comment by metalogical** [comment]
yes, this seems like the best way forward

**Comment by airblade** [comment]
Done via #230.

**Comment by Jeklah** [comment]
Sorry to comment on an old thread, but I just installed kite and I'm getting a message saying template must not contain 'longest' and my googling led me here...sounds like my completeopt has longest in. Whats the fix for this, and how can I make it a permanent fix?

Thanks guys.
