### ISSUE TITLE
Kite not activated on file w/o .py extension

### ISSUE THREAD

**Issue by yochem** [kiteco/vim-plugin#219]
Kite will not be activated when the file opened doesn't have the `.py` extension. This is also true for files without extension, but with Python shebang. I propose Kite will use the language recognition of vim itself.

## Reproducing
- ```echo "#!/usr/bin/env python3" > no_extension; vim no_extension```
Start typing and notice Kite is not enabled.
- ```vim extension.py```
Start typing and notice Kite is enabled.

## Versions
- nvim v0.4.2
- vim 8.0
- Kite ??

**Comment by airblade** [comment]
It used to work that way but was changed in aaa7355.  I can't remember exactly why but I think it was to avoid Kite being activated on a type of Python file where it wouldn't be useful.

@jansorg Can you remember more?

**Comment by airblade** [comment]
Done in #223.
