### ISSUE TITLE
Ellipsis not rendering on Windows

### ISSUE THREAD

**Issue by airblade** [kiteco/vim-plugin#225]
In Kite's [Vim video](https://www.youtube.com/watch?v=RnVoeGwkpfo&feature=youtu.be) one can see that the ellipsis character isn't rendering properly.  Instead there's an upside down question mark.

<img width="927" alt="Screenshot 2019-10-11 at 9 19 06 am" src="https://user-images.githubusercontent.com/7265/66636605-7008da80-ec09-11e9-9ce5-05647cbc0dd3.png">

This is what it should look like:

<img width="566" alt="Screenshot 2019-10-11 at 9 28 25 am" src="https://user-images.githubusercontent.com/7265/66636634-831baa80-ec09-11e9-8057-55c7f1e73518.png">
 
This is similar to #222 except there the plugin was generating the symbol; here the ellipsis is coming directly from kited.

**Comment by metalogical** [comment]
this can & should be fixed via a back-end change
