### ISSUE TITLE
Union types in completions unwieldy

### ISSUE THREAD

**Issue by adamsmith** [kiteco/vim-plugin#226]
![Screen Shot 2019-10-11 at 11 58 58 AM](https://user-images.githubusercontent.com/87728/66677516-a7ce4d00-ec1e-11e9-872a-d35590653461.png)

We should probably truncate after a certain number of chars.

Atom:

![Screen Shot 2019-10-11 at 12 03 32 PM](https://user-images.githubusercontent.com/87728/66677745-304ced80-ec1f-11e9-8b7d-29c2e7d315ef.png)

VS Code:

![Screen Shot 2019-10-11 at 12 03 45 PM](https://user-images.githubusercontent.com/87728/66677751-34790b00-ec1f-11e9-946f-249e21990892.png)

**Comment by metalogical** [comment]
I agree that the client should truncate. But it should be fairly generous with the number of characters allowed (either vs code or atom seem reasonable, but vs code's is preferable if that appears ok in vim).

**Comment by adamsmith** [comment]
I don't know if this is possible but it would also be great if we could style the type string in the completions UI to be lower contrast than the completion text on the left, as in VS Code and Atom.

**Comment by airblade** [comment]
@adamsmith Sadly that's not possible with the completions window.

**Comment by airblade** [comment]
What's the rule for truncating individual types?  In the VS Code screenshot the first type (`numpy.bool...`) is truncated after 10 characters but the second has 15.

Is there a guideline for maximum desired width?

**Comment by adamsmith** [comment]
Let's set the max width of the completions results to 45 chars total, including the variable name, the spacing between the variable name and the type string, and the type string. 

This is inspired by how VS Code does it:

![Screen Shot 2019-10-15 at 10 21 35 AM](https://user-images.githubusercontent.com/87728/66854328-fdb03700-ef35-11e9-9e72-c4bdc08d9e91.png)

![Screen Shot 2019-10-15 at 10 24 51 AM](https://user-images.githubusercontent.com/87728/66854363-0acd2600-ef36-11e9-980a-551205af4b4c.png)

**Comment by airblade** [comment]
Please see pull request #229.
