### ISSUE TITLE
completions requests not made when deoplete installed and custom completeopt

### ISSUE THREAD

**Issue by metalogical** [kiteco/vim-plugin#237]
I have deoplete installed, and it's correctly disabled when entering a Kite-supported buffer. This may or may not be related.

I have the following in my `init.vim` (NeoVim):
```
set completeopt-=preview
set completeopt-=longest
set completeopt+=noinsert
```
In a Python buffer, when I type, no completions requests are sent to `kited`, and `completeopt=menu,noinsert`

If I remove the custom `set completeopt` lines, everything works.

**Comment by airblade** [comment]
In this case deoplete is unrelated.

No completion requests are made because your `completeopt` doesn't contain `menuone`, and you can't see the warning message because of #236.

**Comment by metalogical** [comment]
Gotcha. This would be confusing for users: I set those options with a previous version of the vim plugin (based on the readme), and now with the latest version, setting those options breaks the desired behavior.
