### ISSUE TITLE
Make tab the default way to select a completion

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#238]
This came from user feedback. I'm not super familiar with the landscape of Vim completions, but if the tab key is the generally accepted way to select a completion, I suggest making it the default for Kite as well.

**Comment by airblade** [comment]
I disagree.  The default way in Vim to accept a completion is `<C-Y>`.  Using tab is popular but it's not the default.

If someone wants to use tab, the readme explains how:

> Normally you insert the currently selected completion option with `<C-y>`.  If you'd like to use `<Tab>` instead / as well, add this to your vimrc:
> 
>    let g:kite_tab_complete=1
>

**Comment by its-dhung** [comment]
Got it. Perhaps we need to have better onboarding to educate users about these settings then. Will think about this a bit.

**Comment by airblade** [comment]
One approach would be to make better use of Vim's built-in documentation mechanism, i.e. `:help some-topic`.

I think Vim users would expect to be able to do `:help kite-completions` and get all the relevant info.  At the moment all they get is [doc/kite.txt](https://github.com/kiteco/vim-plugin/blob/9da5d7b878cf85ce8646b332c056f07c78f8ee9d/doc/kite.txt).

**Comment by jansorg** [comment]
@its-dhung Should @airblade implement `:help kite-completions` or would you like something else?

**Comment by airblade** [comment]
See also #154.

**Comment by metalogical** [comment]
closing in favor of #154
