### ISSUE TITLE
unwanted completions frequently inserted when return is pressed

### ISSUE THREAD

**Issue by sinan-kite** [kiteco/vim-plugin#244]
I find unwanted completions are frequently inserted when I press return at the end of a line. Is it possible to configure kite so completions are not inserted when return is pressed?

**Comment by airblade** [comment]
Please could you elaborate a little?

Is this when you press return after normal editing?  Or is it when you accept a completion by pressing return?  Or accept a completion with `<C-y>` and then press return?

Also, have you got auto-completion on (`:echo g:kite_auto_complete`)?

**Comment by sinan-kite** [comment]
when completions appear, I can insert a completion by pressing return, but I would like to disable that and always use `<C-y>` or possibly tab because its frequently the case that completions are shown when I want to use return in the usual way. I know I can use `let g:kite_tab_complete=1` to configure "tab complete", but I don't know how to configure "return complete".

`:echo g:kite_auto_complete` shows `1`

**Comment by airblade** [comment]
Thanks for the extra details.

The way completions work in Vim, pressing enter will insert the current completion choice followed by a line break – unless you have simply changed the completion choice with ctrl-n / ctrl-p / cursor keys, in which case no line break is inserted.

From vim's help (`:help ins-completion-menu`):

> There are three states:
> 1. A complete match has been inserted, e.g., after using CTRL-N or CTRL-P.
> 2. A cursor key has been used to select another match.  The match was not
>    inserted then, only the entry in the popup menu is highlighted.
> 3. Only part of a match has been inserted and characters were typed or the
>    backspace key was used.  The list of matches was then adjusted for what is
>    in front of the cursor.
>
> You normally start in the first state, with the first match being inserted.

[snip]

> If you select another match, e.g., with CTRL-N or CTRL-P, you go to the first
state.  This doesn't change the list of matches.

[snip]

> The behavior of the `<Enter>` key depends on the state you are in:
> first state:	  Use the text as it is and insert a line break.
> second state:	  Insert the currently selected match.
> third state:	  Use the text as it is and insert a line break.
>
> In other words: If you used the cursor keys to select another entry in the
> list of matches then the <Enter> key inserts that match.  If you typed
> something else then <Enter> inserts a line break.

If you want `<enter>` never to insert a completion, that's not the way Vim works.  I suppose we could add an option which maps `<enter>` to `<C-e><CR>` when the popup menu is open.  But perhaps you could try that first in your vimrc to see if it does what you want.

```viml
imap <expr> <CR> pumvisible() ? "\<C-e>\<CR>" : "\<CR>"
```

**Comment by airblade** [comment]
Ah, probably the plugin is over-writing the mapping.  Please could you try just setting by hand in vim once you have a Python file open, to see if it helps?

**Comment by sinan-kite** [comment]
that doesn't work either. also setting `:imap <cr> test` by hand from inside vim doesn't have any effect.

**Comment by airblade** [comment]
What does `:imap <cr>` show?

**Comment by sinan-kite** [comment]
with `imap <CR> test1` in my vimrc, after opening vim `:imap <CR>` shows:

```
i  <CR>         @kite#completion#popup_exit("\<CR>")
i  <CR>          test1
```

after setting `:imap <CR> test2` by hand from inside vim, then `:imap <CR>` shows

```
i  <CR>         @kite#completion#popup_exit("\<CR>")
i  <CR>          test2
```

the test1 map and test2 map dont seem to have any effect. I can still use <cr> to insert line breaks and accept completions.

**Comment by sinan-kite** [comment]
if I set `:imap <buffer> <expr> <CR> pumvisible() ? "\<C-e>\<CR>" : "\<CR>"` by hand from inside vim, then it works exactly as hoped. but putting this in my vimrc doesn't work unfortunately.

**Comment by sinan-kite** [comment]
the map gets overwritten whenever theres a new buffer, but putting `autocmd InsertEnter * imap <buffer> <expr> <CR> pumvisible() ? "\<C-e>\<CR>" : "\<CR>"` in vimrc works.

**Comment by airblade** [comment]
The plugin's mappings are set on `BufEnter` and they are buffer-local so they should only be set once per (Python / Go) buffer.

Your vimrc will be read before the plugin which is why your test maps were getting overwritten.  Anyway, I'm glad you found a solution.

Are you happy to close this issue now?

**Comment by sinan-kite** [comment]
ya, thanks!
