### ISSUE TITLE
Weird recursive suggestion of `...)`

### ISSUE THREAD

**Issue by yochem** [kiteco/vim-plugin#245]
Hi,

When you forget to terminate a string in a function argument, you get `...)` as suggestion, with each suggestion being one `...)` more than the one before.

## Versions:
- Kite: 0.20191205.2
- NeoVim: v0.4.3

## Minimal working example
Open a new file in nvim:
```bash
nvim test.py
```
Enter insert mode and type:
```python
print('a)<cursor here>
```

## Screenshot
<img width="952" alt="image" src="https://user-images.githubusercontent.com/23235841/70662574-cd9bc080-1c66-11ea-965b-05989b1db859.png">

I don't think this is a bug per se, but rather a unintended side effect.

**Comment by airblade** [comment]
That looks quite artistic :)

**Comment by airblade** [comment]
I can't reproduce this with nvim 0.4.0-dev, kite 20191211.1, and 5ef203a.

**Comment by yochem** [comment]
Hhmm too bad. I've investigated some more: I can't reproduce with `nvim -u NORC test.py` and doing the steps above, so the problem seems to be in my vimrc file.

Kite related settings from vimrc:
- `let g:kite_tab_complete=1`
- `set completeopt-=preview`
- `set completeopt+=menuone,noinsert`

What's weird is that as of today, I don't see the error anymore. My Kite is updated to `0.20191212.1`. Maybe it's fixed already? I'll reopen this issue if I still encounter the problem.
