### ISSUE TITLE
if I use powerline, how to integrate it?

### ISSUE THREAD

**Issue by czw0078** [kiteco/vim-plugin#246]
Hi. I currently use the
https://github.com/powerline/powerline
as my vim status line plugin. How should I also display the kite information in the powerline status? Or should I switch to https://github.com/vim-airline/vim-airline because it is pure vim script status-line and no need python?

**Comment by airblade** [comment]
From the [readme](https://github.com/kiteco/vim-plugin#statusline):

> Add `%{kite#statusline()}` to your statusline...

I'm not familiar with how to add information to Powerline's status display, nor Airline's; you'll have to ask them.  But all the status display needs to do is call the function `kite#statusline()`.

**Comment by airblade** [comment]
Please let me know if you have any other difficulties.

**Comment by geekyarthurs** [comment]
Any help?

**Comment by airblade** [comment]
@geekyarthurs With what?

**Comment by geekyarthurs** [comment]
I use airline, anyway to connect it with kite?

**Comment by airblade** [comment]
Please see https://github.com/vim-airline/vim-airline/wiki/Configuration-Examples-and-Snippets.

You just need to call `kite#statusline()`.
