### ISSUE TITLE
golang filetype

### ISSUE THREAD

**Issue by ErrEoE** [kiteco/vim-plugin#250]
Why support golang filetype? I used it , but not any autocomplete action. This cause go Can I disable it by settings?
```
function! s:supported_language()
  return (&filetype == 'python' && expand('%:e') != 'pyi') || &filetype == 'go'
endfunction
```

**Comment by plungg** [comment]
@ErrEoE we just turned on golang support for beta users. Let me know if you're interested in trying this out!

**Comment by ErrEoE** [comment]
Can we use a settings disable it ?

**Comment by plungg** [comment]
Is this change causing issues for you? There is currently no setting to disable it, but we'd like to learn why you want this disabled.

**Comment by ErrEoE** [comment]
Because this will disable ycm for golang filetype.

**Comment by plungg** [comment]
Thanks for letting us know. We won't have a fix until early Jan as the team is off for the holidays.

**Comment by ErrEoE** [comment]
thanks for your help!

**Comment by plungg** [comment]
A fix in the backlog. Thanks for your patience.

**Comment by jansorg** [comment]
To be implemented with a runtime check of supported languages, but just to enable/disable support for Golang .

**Comment by airblade** [comment]
Done in #252.  By default Kite's Go support is disabled.
