### ISSUE TITLE
can not remove kite cleanly

### ISSUE THREAD

**Issue by laoshaw** [kiteco/vim-plugin#256]
that gave me a feeling of malware. I could not remove kite on ubuntu easily.

1. uninstall kited
2. cd $HOME/.local/share/kite and run ./uninstall
3. cd $HOME/.config && rm -rf Kite

still whenever I use vim it has this "Kite: disabling YouCompleteMe's completition for python files", note I had nothing in .vimrc refer to Kite.

This code must be installed and uninstalled cleanly to gain trust. For now I'm back to YCM

**Comment by its-dhung** [comment]
Hi @laoshaw, plugins must be uninstalled before uninstalling the Kite app. Given that you already uninstalled Kite, you should be able uninstall the Vim plugin with the command:

```
rm -rf ~/.vim/pack/kite
```

Please re-open if this doesn't fix your issue for you.

**Comment by laoshaw** [comment]
ok, I further removed $HOME/.kite, $HOME/.vim/pack/kite and now it seems "clean"

**Comment by cero1010** [comment]
kite is absolutely a malware

**Comment by cero1010** [comment]
finally  I removed the malware Kite. The developers are mother fuckers!

**Comment by adamsmith** [comment]
Hi, we deleted two comments that were abusive. Closing this thread.
