### ISSUE TITLE
Intelligent Snippets's error in neovim 

### ISSUE THREAD

**Issue by ErrEoE** [kiteco/vim-plugin#257]
```

# -*- coding: utf-8 -*-

import os
os.path.join([a], [filename])
```
when i enter `ctrl +j` on '[a]', neovim show error message:

![image](https://user-images.githubusercontent.com/14369333/73925713-6bc7a200-4909-11ea-9013-6b0feeccbd5a.png)

**Comment by airblade** [comment]
This is how I tried to reproduce:

- Touch an empty Python file and open it in NeoVim (or Vim).
- Type up to `os.path.j` and then use `<C-X><C-U>` to trigger Kite's autocompletion.
- Type `<C-Y>` to accept `...(<a>, <filename>)` and jump back to the first snippet (`[a]`).
- Type `<C-j>`.  As expected this jumps to the next snippet (`[filename]`).

So I wasn't able to reproduce the error.

Please could you tell me what commit your Kite vim plugin is at?

Do you get the error every time?

**Comment by ErrEoE** [comment]
I use kite vim plugin' s version is 1.0.61, neovim's version is 0.5.0.
I get the error every time.

**Comment by airblade** [comment]
> If you input a char on first snippet ([a]), and type C-k, then the error occur.

I get that too.  Thanks for the tip.

**Comment by airblade** [comment]
It seems to depend on whether the character you type has any potential completions (e.g. `x`) or not (e.g. `y`).

**Comment by airblade** [comment]
Please could you try the fix in #259?

**Comment by ErrEoE** [comment]
I try #259,
![E)ETI6G7I02`5FL62$G G_7](https://user-images.githubusercontent.com/14369333/74314202-031c7180-4db0-11ea-9d13-9d399dd925d0.png)

**Comment by airblade** [comment]
Do you type `1` immediately after accepting the `join()` completion with `<C-Y>`?  In other words, when the first snippet is selected?

When I do that, and then type `<C-j>`, it works as expected.

**Comment by airblade** [comment]
`^@` is a null byte.  I don't know why you're seeing this.

**Comment by ErrEoE** [comment]
when I type `c-n`, the `join([a], [filename])` is autocomplete, I don't type `c-y`.
