### ISSUE TITLE
Notify user if they are using an unsupported Vim version

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#262]
If a user is using Vim 7 or below, let them know Kite doesn't support their editor.

https://stackoverflow.com/questions/60245846/vim-error-each-time-programs-py-new-file-error-detected-while-processing-fu

**Comment by airblade** [comment]
Do you happen to know what Vim version the installer checks for?  It would be good to make the plugin consistent with the installer.

**Comment by jansorg** [comment]
@airblade The installer accepts version `8.0.0027` and later.
