### ISSUE TITLE
follow cursor doesn't work until leaving insert mode

### ISSUE THREAD

**Issue by metalogical** [kiteco/vim-plugin#264]
It looks like we must not send the updated cursor position with the buffer event until the user leaves insert mode, which is annoying when depending on follow cursor behavior.

Is it possible to properly send the events while the user is in insert mode? @airblade

**Comment by airblade** [comment]
I presume this is the selection event?

We send the selection event shortly (default 100ms) after leaving insert mode; and the edit event whenever the text changes, whether in normal or insert mode.

https://github.com/kiteco/vim-plugin/blob/89896b370a4bfb889af67e94d21d1e5e2b61054d/autoload/kite.vim#L119-L120

By comparison the plugin provides docs on hover in both insert and normal modes:

https://github.com/kiteco/vim-plugin/commit/9a2746e4812851d84aefbc46c037cd54c628431a#diff-96aea571c2ebf3a5a0d2e56baa521a59

I can't think of any reason not to send the selection event while still in insert mode.  I'll open a pull request for this.

**Comment by airblade** [comment]
Fixed in #265.
