### ISSUE TITLE
Maybe we need custom shortcut 

### ISSUE THREAD

**Issue by AutoColin** [kiteco/vim-plugin#267]
For me <C+keys> is not so convenient so I think maybe Kite can allow us to custom some shortcuts?
For example, the shortcut to switch completion, which is **<C+n>/<C+p>**, can be altered to 
 **<A+n>/<A+p>** or some other binds?

**Comment by airblade** [comment]
Those are Vim's default keys for completions (see `:help ins-completion-menu`), not Kite's.

You can of course map other keys to do this but that's outside the scope of this plugin.

I think mapping the alt key can be a little tricky sometimes, depending on your terminal, but I'm sure it's always possible.

**Comment by airblade** [comment]
Closing this now but feel free to open a new issue if you have any further problems.  Thanks!
