### ISSUE TITLE
Error when I open the file: You may need to restart your editor for changes to take effect.

### ISSUE THREAD

**Issue by tangzhe0220** [kiteco/vim-plugin#268]
when I type "vim *.py",  the error message always poped up "You may need to restart your editor for changes to take effect.". I tried to reinstall Kite but still doesn't work. Does anyone know how to fix this error?

**Comment by airblade** [comment]
I don't think this error message is coming from the Vim plugin; I think it is coming from the Kite process.

@jansorg It sounds like https://github.com/kiteco/atom-plugin/issues/641 and https://github.com/kiteco/atom-plugin/issues/644.

**Comment by jansorg** [comment]
@tangzhe0220 Is the error message shown inside of the vim terminal window or in a separate window?

**Comment by jansorg** [comment]
Results of last week's investigation: This seems to be related to the automatic start of Kite when the Vim with the vim-plugin is launched. For yet unknown reasons the Copilot is launched by Kite (it shouldn't) and attempts to update on of the plugins (it shouldn't).

**Comment by tangzhe0220** [comment]
> @tangzhe0220 Is the error message shown inside of the vim terminal window or in a separate window?
> are you on windows?

My system is MacOS, not windows.

**Comment by tangzhe0220** [comment]
> Results of last week's investigation: This seems to be related to the automatic start of Kite when the Vim with the vim-plugin is launched. For yet unknown reasons the Copilot is launched by Kite (it shouldn't) and attempts to update on of the plugins (it shouldn't).

How should I do to fix this problem? I tried to start Kite and then launched vim, but didn't work even.

**Comment by jansorg** [comment]
@tangzhe0220 This is a weird issue. Could you post a screenshot of the error message, please?
Could you also report the output of the vim command `:echo kite#utils#plugin_version()`, please?

**Comment by airblade** [comment]
This has gone quiet so I'm going to close it.  Please open a new issue if you have any further problems.  Thanks!
