### ISSUE TITLE
Kite require to start my Neovim editor to take effect.

### ISSUE THREAD

**Issue by baonlt99** [kiteco/vim-plugin#269]
Hello 
I am quite confused about this alert and have no idea to fix it. I am tried to reinstall Neovim a couple of times but it didn't work even.
![image](https://scontent.fsgn5-7.fna.fbcdn.net/v/t1.15752-9/94067289_1050811221968706_4979922555742715904_n.png?_nc_cat=103&_nc_sid=b96e70&_nc_ohc=GmR1jFQe6jQAX9sArxi&_nc_ht=scontent.fsgn5-7.fna&oh=221000929e39c013dfbb67cc8e7b31f6&oe=5EC436E8)

**Comment by airblade** [comment]
Hello,

It just means you might need to quit Neovim and restart it.
