### ISSUE TITLE
Kite doesn't work at all in Cygwin on Windows

### ISSUE THREAD

**Issue by Jeklah** [kiteco/vim-plugin#272]
[kiteNotWorking.zip](https://github.com/kiteco/vim-plugin/files/4577293/kiteNotWorking.zip)
I've attached my .vimrc.local file with the settings for kite in and some logs that have been generated while writing python in vim, with nothing from kite. Statusbar doesn't show the Kite Status either even using the suggested command.

The only thing that does work is I can type :k and push tab and the Kite commands come up. KiteTutorial brings up a black pop up box that made me think it's installed but not set up right but I'm not sure where I've gone wrong.

It'd be great if I could get this working. 
Thanks.

**Comment by airblade** [comment]
Thanks for those files.

It looks like the languages endpoint works (`/clientapi/languages`) but all the completion requests are returning a 400 HTTP status code along with the error message:

    non absolute path /cygdrive/d/Projects/eveOnline/scripts/ships.py

@jansorg Is the vim plugin sending the path in the wrong format?

**Comment by Jeklah** [comment]
Thanks for getting back to me.
How can I check?

**Comment by jansorg** [comment]
@airblade cc @Jeklah 
It seems that Vim is executed in a Cygwin shell on Windows. Is that the case?
So far Kite is only supporting native Vim on Windows, e.g. from https://github.com/vim/vim-win32-installer/releases .

**Comment by Jeklah** [comment]
Yes I am running it in a Cygwin shell on Windows.
Shame that isn't supported.
Are there any future plans to support this?

**Comment by jansorg** [comment]
@Jeklah Supporting Cygwin isn't planned at this time.

**Comment by jansorg** [comment]
@Jeklah Do you have a particular use-case why you prefer Cygwin Vim over the native Vim on Windows?

**Comment by Jeklah** [comment]
> @Jeklah Do you have a particular use-case why you prefer Cygwin Vim over the native Vim on Windows? 

I have a cygwin setup that I use, usually with tmux and vim within that. Basically because I prefer CLI to dealing with windows in Windows 10. I also play games. 
I don't think it's worth installing a dual boot or even the new windows Linux just to get a shell I like when I can use the cygwin setup I already have configured.

**Comment by airblade** [comment]
@metalogical Are there any plans for supporting Cygwin or should this issue be closed?

**Comment by Jeklah** [comment]
There are no plans to get it to work in cygwin. Issue can be closed.

Note: I am not a Kite dev but this is what a Kite dev told me in an email.
