### ISSUE TITLE
Documentation is truncated in preview window

### ISSUE THREAD

**Issue by ganeshaaradhya** [kiteco/vim-plugin#274]
Hi ,

This is Ganesh. First of all GREAT JOB!! i am using from past 2 weeks it is just what i was looking for python coding in vim.

Documentation in preview window will be truncated if function doc is very big
Ex: 
In preview window for np.lexsort()

<img width="704" alt="doc_preview" src="https://user-images.githubusercontent.com/50175048/81734513-3d7dd380-94b1-11ea-90e9-b5b8d2c13599.png">

In copilot for np.lexsort()

<img width="261" alt="copilot" src="https://user-images.githubusercontent.com/50175048/81734806-b9781b80-94b1-11ea-97e6-11267caaf115.png">

I dont like using multiple tabs opened. If it loads the whole documentation in preview window it would help a lot.

Thanks in advance

**Comment by airblade** [comment]
I don't know why this is happening.  The plugin doesn't truncate the text:

https://github.com/kiteco/vim-plugin/blob/d5bde6c2686d09b4ccdbb9166526c37384831568/autoload/kite/completion.vim#L281

So either Vim's preview window only takes a limited amount of text (I can't find any information suggesting this might occur) or Kite is returning truncated text.

@jansorg Could Kite be returning truncated text?

**Comment by ganeshaaradhya** [comment]
As i can see, it is happening both in nvim and vim. So probability of vim taking limited amt of space is less

**Comment by jansorg** [comment]
At this time Kite is trucating the docs to limit the size of the completions response. We're thinking of improvements here for the future.

**Comment by ganeshaaradhya** [comment]
Thanks jansorg, is there a way to open copilot in terminal. Suppose we are using tmux kind off

**Comment by jansorg** [comment]
@ganeshaaradhya Unfortunately that's not possible. Copilot only comes with a UI

**Comment by ganeshaaradhya** [comment]
is there any plans to enable it?

**Comment by airblade** [comment]
@ganeshaaradhya I don't think there are any plans to convert Copilot into a terminal / CLI app.
