### ISSUE TITLE
Don't show "Disabling YouCompleteMe's completion for python files"

### ISSUE THREAD

**Issue by yochem** [kiteco/vim-plugin#276]
Hi maintainers,

I absolutely love this autocomplete package for vim, but use more languages than Python. That's why I've started using YouCompleteMe. I now use YCM alongside Kite. But even though YCM is disabled for the Python filetype, I still *always* get the message "Disabling YouCompleteMe's completion for python files". I think it's okay to show this message if Python isn't on the YCM blacklist, but why show it if Python is on the YCM blacklist?

## Suggestions
I propose checking if python is on the blacklist of each other autocomplete engine. This would look like something in the line of:

```diff
-if exists('g:loaded_youcompleteme')
+if exists('g:loaded_youcompleteme') && !exists('g:ycm_filetype_blacklist.python')
     let g:ycm_filetype_blacklist.python = 1
     call kite#utils#warn("disabling YouCompleteMe's completions for python files")
 endif
```

Another option would be to just remove the message and don't let the user know YCM is being disabled. 

## Pro's
- No more 'random' messages everytime a python buffer is opened

## Cons
- Someone needs to find out how the blacklist is stored for all other completion engines and add these in
- There are multiple blacklists, especially with YCM: `g:ycm_filetype_blacklist`, `g:ycm_filetype_specific_completion_to_disable` which makes it harder to keep track of it.

Please let me know what you think about this issue. Glad to help if there's anything I can do.

**Comment by airblade** [comment]
Thanks for the suggestion – it sounds like a good idea.  We'll try to implement it soon.

**Comment by airblade** [comment]
Thanks again.
