### ISSUE TITLE
Autocomplete for JavaScript (Neovim)

### ISSUE THREAD

**Issue by henryoliver** [kiteco/vim-plugin#281]
Hi there, I just bough Kite Pro and start to use it on my IDE (Neovim). Python is working great so far, but I can't get JavaScript to work for some reason. Can you guys help me out?

JavaScript is 90% of my work related language, and I would like to make this work as showing on the example below:
https://www.kite.com/javascript/

Thanks
-- Henry

**Comment by jansorg** [comment]
@henryoliver , JS support for VIM is on its way and should be released next week. 
https://github.com/kiteco/vim-plugin/pull/279 contains the changes and details how to enable when it's released.

**Comment by henryoliver** [comment]
Great @jansorg! How about Copilot?
```
Kite suggests JavaScript completions as you code in your editor. However, the Copilot does not have JavaScript docs.
```
By the way, congratulations on the awesome job you guys did on this tool. If that works I'm even considering drop entirely my current autocompletion plugin and my offline documentation tool. And of course, spread the word. :)

Thanks again!
-- Henry

**Comment by airblade** [comment]
@henryoliver Kite has supported JS for a few months now so I'm going to close this.  Please open a new issue if you have any further problems.  Thanks!
