### ISSUE TITLE
Error: Kite: completeopt must not contain 'longest'

### ISSUE THREAD

**Issue by austinmw** [kiteco/vim-plugin#282]
I'm using spacevim with neovim and hitting this error:
https://github.com/kiteco/vim-plugin/blob/810bdcc98a33516498f8cfc0d4bd0ff6d86a8934/autoload/kite/completion.vim#L387

I think I've disabled anything jedi/jedi-vim/deoplete-jedi related in my python.vim layer. 

Any idea what might be wrong? Thanks!

**Comment by airblade** [comment]
You can do `:verbose set completeopt` to find out where it was set.

**Comment by airblade** [comment]
As of d437cde your `completeopt` values can contain `longest`.
