### ISSUE TITLE
Disable YCM completions for Python only if kited is available

### ISSUE THREAD

**Issue by adamsmith** [kiteco/vim-plugin#283]
How difficult would this be to do?

See https://github.com/kiteco/vim-plugin/issues/256.

**Comment by airblade** [comment]
The plugin has a function which detects [whether kited is available](https://github.com/kiteco/vim-plugin/blob/810bdcc98a33516498f8cfc0d4bd0ff6d86a8934/autoload/kite/utils.vim#L136).

Currently it is only used by the code which [updates the status line](https://github.com/kiteco/vim-plugin/blob/810bdcc98a33516498f8cfc0d4bd0ff6d86a8934/autoload/kite/status.vim#L15).

Would it would make sense for the plugin to deactivate itself completely if kited is unavailable?

**Comment by metalogical** [comment]
The ideal behavior would be to disable completions until Kite becomes available, at which point we could deactivate YCM (and others) and enable completions.

Would this be difficult with the current architecture?

**Comment by airblade** [comment]
Shouldn't be too hard.  I'll work on it.

**Comment by airblade** [comment]
Done in #284.
