### ISSUE TITLE
work fine until chinese characters appear

### ISSUE THREAD

**Issue by Lqingyi** [kiteco/vim-plugin#285]
my code is like this:

`import os`
`os.path`
`"汉字"`
`os.path`

when i typed the firse `os.path`,completions automatically appeared,but when i typed second `os.path`,nothing appeared

**Comment by Lqingyi** [comment]
the environment is VIM8.2 MS-Windows 64-bit GUI version With OLE win7/10

**Comment by airblade** [comment]
With this text:

```
import os
os.path
"汉字"
os.p
```

– and the cursor after the `p` on the last line, triggering completion shows this in the log:

```
> POST /clientapi/editor/event HTTP/1.0
> Host: localhost
> Content-Type: application/x-www-form-urlencoded
> Content-Length: 223
>
> {"selections":[{"end":26,"start":26}],"source":"vim","action":"selection","editor_version":"8.2.1-607","plugin_version":"1.0.67","text":"import os\nos.path\n\"汉字\"\nos.p\n","filename":"/Users/andy/code/src/ramp/285.py"}
| Received complete response: 13.305ms
< HTTP/1.0 200 OK
< Date: Mon, 15 Jun 2020 09:51:46 GMT
< Content-Length: 0
```

@jansorg I believe the plugin is sending the correct JSON – would you agree?  If so, the problem must be in kited.

**Comment by airblade** [comment]
If I type the `a` (so the last line is `os.pa`) the completion starts to work but it's offering me completions for `os`.  This suggests that the offsets are wrong: either the plugin is sending the wrong offsets or kited is misinterpreting them.

Unless it characters versus bytes?

<img width="243" alt="Screenshot 2020-06-15 at 10 57 12 am" src="https://user-images.githubusercontent.com/7265/84644484-23dc0b80-aef7-11ea-997b-7894f8eac2f3.png">

**Comment by jansorg** [comment]
@airblade kited was updated to accept an encoding for the offset, could you please try to send `"offset": "utf-32"` along with `start` and 'end`?
The complete json would be :
```json
{
  "selections": [
    {
      "end": 26,
      "start": 26,
      "offset": "utf-32"
    }
  ],
  "source": "vim",
  "action": "selection",
  "editor_version": "8.2.1-607",
  "plugin_version": "1.0.67",
  "text": "import os\nos.path\n\"汉字\"\nos.p\n",
  "filename": "/Users/andy/code/src/ramp/285.py"
}
```

**Comment by airblade** [comment]
@jansorg That didn't help unfortunately.  I'm on Kite 0.20200609.2.

Since the file encoding in Vim is UTF-8 I tried sending 'utf-8' as the `offset` but it didn't help either.

**Comment by jansorg** [comment]
@airblade Sorry, I had sent you the wrong property name. It's `encoding` for the events requests.
And there's an additional `offset_encoding` property for the completions request.

Here's a diff to master, which seems to make this to work for me:
```
diff --git a/autoload/kite/completion.vim b/autoload/kite/completion.vim
index f3f610a..de538e5 100644
--- a/autoload/kite/completion.vim
+++ b/autoload/kite/completion.vim
@@ -155,7 +155,8 @@ function! s:get_completions()
           \   'filename':     filename,
           \   'editor':       'vim',
           \   'text':         s:text,
-          \   'cursor_runes': s:cursor
+          \   'cursor_runes': s:cursor,
+	  \   'offset_encoding': 'utf-32'
           \ }
   else
     let params = {
@@ -168,7 +169,8 @@ function! s:get_completions()
           \     'begin': (s:begin > 0 ? s:begin : s:cursor),
           \     'end':   (s:end   > 0 ? s:end   : s:cursor),
           \   },
-          \   'placeholders': []
+          \   'placeholders': [],
+	  \   'offset_encoding': 'utf-32'
           \ }
     let s:begin = 0
     let s:end   = 0
diff --git a/autoload/kite/events.vim b/autoload/kite/events.vim
index 7f1c33c..a662884 100644
--- a/autoload/kite/events.vim
+++ b/autoload/kite/events.vim
@@ -20,7 +20,7 @@ function! kite#events#event(action)
   if [sel_start, sel_end] == [-1, -1]
     return
   endif
-  let selections = [{ 'start': sel_start, 'end': sel_end }]
+  let selections = [{ 'start': sel_start, 'end': sel_end, 'encoding': 'utf-32' }]
 
   let json = json_encode({
         \ 'source':     'vim',

```

**Comment by airblade** [comment]
@jansorg That works for me too.

Why `utf-32`?  The file itself is UTF-8.

I opened a PR for this: #287.

**Comment by jansorg** [comment]
@airblade Thanks, I'll review the PR. It's `utf-32` because it's defining the encoding of the offset, not of the content. Vim is sending character offsets, which is identical to offsets in utf-32 encoded content.
The content is send as JSON and is therefore encoded as JSON and not in a utf-x encoding. At least I hope that my understanding is correct here...

**Comment by metalogical** [comment]
Yes. The default encoding of "correct" JSON is always UTF-8, so actually all clients send the buffer text UTF-8-encoded (with some oddities regarding escaped unicode characters).

Setting the offset_encoding to utf-32 here tells Kited to first re-encode the buffer text as UTF-32 before using the offset as a count of number of "code units" into the buffer. A code unit is 8, 16, or 32 bits long for UTF-8, 16, and 32, respectively.

In the case of Vim, the offset counts unicode characters. This is equivalent to counting the number of 32-bit code units if the text were to be encoded as UTF-32, since every character takes exactly one code unit in UTF-32.

**Comment by airblade** [comment]
@jansorg @metalogical Thanks for the explanations!  I understand now.
