### ISSUE TITLE
How to install Kite on remote machine without sudo?

### ISSUE THREAD

**Issue by sabetAI** [kiteco/vim-plugin#289]

**Comment by airblade** [comment]
Kite's vim plugin (this repo) is a normal plugin and you can install it the way you install your other plugins.

However it relies on Kite's own application – @jansorg how would one install that remotely?

**Comment by jansorg** [comment]
@sabetAI Is this about Linux systems? A recent change of kite now allows it to be installed on Linux without a ui. Ssh into your remote machine and run the command shown on kite.com. Does that work for you? Sudo is not required.

**Comment by jansorg** [comment]
@sabetAI The current version of Kite can now be installed with and without sudo on a remote (i.e. headless) environments. Please reopen if this isn't working for you.
