### ISSUE TITLE
Implement goto definition

### ISSUE THREAD

**Issue by its-dhung** [kiteco/vim-plugin#291]
The `report` field in the [`/hover`](https://kite.quip.com/Cs9vAajPr6y9/Unified-Editor-API#AFTACAdSs3F) response should contain the definition of the symbol. For example, here's how the [Sublime plugin](https://github.com/kiteco/KiteSublime/blob/master/lib/assets/hover-panel.html#L23-L25) uses it.

We should implement a command `KiteGotoDefinition` in the Vim plugin, which essentially:
* Queries the `/hover` endpoint to see if there's a definition for the symbol, and if there is, open the file and line number.
* If there is no definition, then display an error message in the command line: `Kite was unable to find a definition`.

**Comment by airblade** [comment]
Do you want `gd` or `gD` mapped to `KiteGotoDefinition`?

**Comment by airblade** [comment]
Done in #292.

**Comment by ysyisyourbrother** [comment]
When I type : KiteGotoDefinition , vim prompts me that it is not an editor command. Is the kite application on the website not the latest version

**Comment by airblade** [comment]
@ysyisyourbrother What does `:echo kite#utils#plugin_version()` say?  `:KiteGotoDefinition` is in v1.0.70.

**Comment by ysyisyourbrother** [comment]
Thanks for your response! After I enter the command, vim told me that my plugin version is 1.0.68. But I just download your app on https://www.kite.com/ and install vim-plugin today.

**Comment by airblade** [comment]
@jansorg Do you know why @ysyisyourbrother has ended up with an old version of the plugin?

**Comment by jansorg** [comment]
I checked, the latest version of vim is not yet in the current release of kite. The release, which bundles it, should be out this week.

**Comment by ysyisyourbrother** [comment]
Thanks a lot! This plugin has brought me great help in my development. I am happy to recommend it to colleagues around me!
