### ISSUE TITLE
:KiteGotoDefinition is not available

### ISSUE THREAD

**Issue by ysyisyourbrother** [kiteco/vim-plugin#298]
When I type :KiteGotoDefinition, vim prompts me that it is not an editor command. Is the kite application which download from the website current not the latest version?

**Comment by airblade** [comment]
Please see https://github.com/kiteco/vim-plugin/issues/291#issuecomment-672783246.

**Comment by ysyisyourbrother** [comment]
Your team member told me to open an issue here so that your product team can look into it.

**Comment by airblade** [comment]
Oh, ok.  Was it this repo or this one: https://github.com/kiteco/issue-tracker?

**Comment by ysyisyourbrother** [comment]
Oh, sorry, my mistake. I will close this one and reopen one on https://github.com/kiteco/issue-tracker
