### ISSUE TITLE
Error detected while processing function kite#events#event[29]

### ISSUE THREAD

**Issue by SanJacobs** [kiteco/vim-plugin#299]
On every keystroke in nvim, I'm getting this error:

```
Error detected while processing function kite#events#event[29]..kite#client#post_event[5]..kite#async#execute:
E117: Unknown function: chansend
Error detected while processing function kite#events#event[29]..kite#client#post_event[5]..kite#async#execute:
E117: Unknown function: chanclose
```

I have tried reinstalling the plugin.
I'm running Ubuntu 18.04.5 LTS and using neovim v0.2.2.

[Here's the link to the Kite-generated application log](https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/4c03b8d4-d99c-41e4-ab13-d5efa123820c/kite_local/client.log.2020-08-19_08-07-36-PM.bak.gz)

**Comment by airblade** [comment]
The plugin only works with neovim v0.3.0+.  Sorry, the version check in the plugin is out of date and it should have warned you.
