### ISSUE TITLE
Edit events setting incorrect selection encoding

### ISSUE THREAD

**Issue by hrysoula** [kiteco/vim-plugin#301]
The selection objects sent in an edit event have `selection.Encoding` set to utf-8, which causes this error: `process event error: could not decode selection start offset: offset not aligned to code point boundary`. The events are utf-32 encoded, so this should be the value set.

**Comment by airblade** [comment]
The vim plugin sets the encoding in edit events to utf-32 (aa4e0fc).

I'm not sure what could be causing the error but @metalogical's comment might be relevant: https://github.com/kiteco/vim-plugin/issues/285#issuecomment-645503457.

**Comment by airblade** [comment]
Are you able to give me steps to reproduce the error please?

**Comment by hrysoula** [comment]
> Are you able to give me steps to reproduce the error please?

You can reproduce this by edit a file with non-ascii characters, e.g. å¼‚æ­¥. You'll see an error in the client log like `error decoding offsets: offset not aligned to code point boundary`.

**Comment by hrysoula** [comment]
cc @metalogical Any idea why the plugin manager does not update to the latest version of the vim plugin?

**Comment by airblade** [comment]
@hrysoula I'm glad the problem has gone away!  Though I'm not sure why as the utf-32 change was in v1.0.69...
