### ISSUE TITLE
How to make <tab> jumps through every selection?

### ISSUE THREAD

**Issue by sangdth** [kiteco/vim-plugin#302]
Currently I have to use up/down arrow key to select, and I can't find anywhere in documentation allow me to configure that behaviour?

**Comment by airblade** [comment]
So when the completion popup window is open you want tab to move down through the options?

```viml
imap <expr> <Tab> pumvisible() ? "\<C-N>" : "\<Tab>"
```

**Comment by sangdth** [comment]
Thank you, that's what I'm looking for.
