### ISSUE TITLE
how to disable enter to select auto complete and just use tab

### ISSUE THREAD

**Issue by ydiizx** [kiteco/vim-plugin#315]
I'm just a beginner, and use kite in vim, usually I use ctrl + enter to move a new line even though there is an autocomplete blocking it, but in vim I'm confused

**Comment by airblade** [comment]
Are you asking how to set things up so that when the autocomplete popup is open, pressing ctrl + enter inserts the selected option plus a carriage return / linefeed?

**Comment by ydiizx** [comment]
I mean kite selects autocomplete when I press enter, I don't want it, and
want to change it using tab or some other key, because every time I press
enter it should create a new line instead selecting autocomplete

Pada tanggal Sen, 16 Nov 2020 pukul 16.54 Andy Stewart <
notifications@github.com> menulis:

**Comment by airblade** [comment]
OK, and when you say "selects autocomplete" do you mean it opens the autocomplete popup, or do you mean it inserts the current option in the already-open autocomplete popup?

**Comment by ydiizx** [comment]
i  mean it inserts the current option in the already-open autocomplete popup

Pada tanggal Sen, 16 Nov 2020 pukul 21.24 Andy Stewart <
notifications@github.com> menulis:

**Comment by airblade** [comment]
Please could you tell me your Vim version and also `:echo &completeopt`?

Also you might like to read `:help ins-completion-menu`.  Here are some excerpts:

```
There are three states:
1. A complete match has been inserted, e.g., after using CTRL-N or CTRL-P.
2. A cursor key has been used to select another match.  The match was not
   inserted then, only the entry in the popup menu is highlighted.
3. Only part of a match has been inserted and characters were typed or the
   backspace key was used.  The list of matches was then adjusted for what is
   in front of the cursor.

...[snip]...

The behavior of the <Enter> key depends on the state you are in:
first state:	  Use the text as it is and insert a line break.
second state:	  Insert the currently selected match.
third state:	  Use the text as it is and insert a line break.

In other words: If you used the cursor keys to select another entry in the
list of matches then the <Enter> key inserts that match.  If you typed
something else then <Enter> inserts a line break.
```

**Comment by airblade** [comment]
In summary, when the insert-mode completion popup is open, you want `<CR>` to exit the popup without inserting any text into the buffer, and insert a line break.

This is all to do with the way Vim handles completions in general, rather than being specifically about this plugin.  You can read how Vim handles `<CR>` in the help doc above.

Maybe something like this would do what you want?

```viml
imap <expr> <CR> pumvisible() ? "\<C-E>\<CR>" : "\<CR>"
```
