### ISSUE TITLE
Allow user to disable Kite completions instead of other third-party completions integrations

### ISSUE THREAD

**Issue by metalogical** [kiteco/vim-plugin#330]
Currently, Kite disables other third-party completions integrations (Deoplete, CoC, LanguageClient-neovim, etc), as multiple completions integrations cannot function properly at the same time.

Given #327, we would like a way for users to demo using a third-party plugin for completions, while continuing to use the Kite plugin for other non-completions features. In order to do this, there needs to be a way to tell Kite to disable it's own completions integration instead of others.

One simple option might simply be a boolean flag `g:disable_kite_completions` which turns off Kite's completions integration.

**Comment by airblade** [comment]
@metalogical Can this issue be closed now?
