### ISSUE TITLE
Report as kite error, nvim error silenced

### ISSUE THREAD

**Issue by Mte90** [kiteco/vim-plugin#336]
![Screenshot_20201228_130701](https://user-images.githubusercontent.com/403283/103213430-eaf10a80-490d-11eb-8b2e-ca39ed60a666.png)

This is what I am getting but that error is silented (with neovim-qt):

```
if exists('g:GuiLoaded')
    Guifont! DroidSansMono\ Nerd\ Font:h10
endif
```

I see something also for vdebug that wasn't started good as kite error.

**Comment by airblade** [comment]
So do those three lines you showed work when the plugin is not installed?

And does the plugin work when those three lines are commented out?

If it helps, this is the only neovim-qt specific code in the plugin:

https://github.com/kiteco/vim-plugin/blob/bdf7f549fa6c03e0afd8bfee4c48e7a8b1e4f168/plugin/kite.vim#L80-L82

It was added in #187.

What version of the plugin are you using?  `:echo kite#utils#plugin_version()`?

**Comment by Mte90** [comment]
Commenting that line doesn't change anything.
The plugin version is 1.0.77

**Comment by airblade** [comment]
Your error message is pointing to this line:

https://github.com/kiteco/vim-plugin/blob/fd5ae30f8917a8760c1d738e302dd9672b664e41/autoload/kite/async.vim#L30

All neovim is doing there is sleeping.

Please could you explain whatyou mean by "vdebug"?

Please could you update the plugin and trying again?

**Comment by Mte90** [comment]
Vdebug is another vim plugin but is not appearing anymore as error.

I don't see any update since my last comment.

**Comment by airblade** [comment]
> I don't see any update since my last comment.

That's odd, the plugin is on 1.0.84 now.  (These are not git tags but [internal version numbers](https://github.com/kiteco/vim-plugin/blob/master/VERSION).)

@metalogical Any idea why the Kite installer isn't updating @Mte90's plugin?

**Comment by Mte90** [comment]
I checked on the github repo and saw no release or new commits in 15 days.
From the Kite tool I don't know how to update it, the tool says 2.20201221.0 and from vim 1.0.77

**Comment by metalogical** [comment]
A new version of Kite was released very recently (2.20210114.0). Please try the following:
1. Update to the latest version of Kite. This will happen automatically if you wait, but you can also manually reinstall.
2. Uninstall/Reinstall the Vim plugin via the Kite plugin manager interface.

Let us know if this solves the problem or if you continue to have issues.

**Comment by Mte90** [comment]
I am trying to update but I am getting this on https://github.com/kiteco/kite-installer/issues/95 from kite itself.

**Comment by Mte90** [comment]
The plugin is at 1.0.84 but I still have the problem

**Comment by airblade** [comment]
OK, it's good you've got the plugin up to date.

I don't really understand the error though.  Are you saying that these lines cause an error:

```vim
if exists('g:GuiLoaded')
    Guifont! DroidSansMono\ Nerd\ Font:h10
endif
```

If they cause an error, does the error go away when those lines are commented out?

**Comment by Mte90** [comment]
I investigated a bit, so this code is for Nvim-qt to hide the error that instead is shown when the kite plugin is enabled.
If I remove `set guifont=DroidSansMono\ Nerd\ Font:h10` nvim-qt loads without any error shown. If I run nvim on terminal I have the same font configured so there are no issues without that line.

So my guess is that I can remove that configuration from my vim as I am using this font everywhere. Otherwise I have the idea that with the kite plugin if there are some nvim-qt errors (not from nvim) this error happens.

**Comment by airblade** [comment]
Thanks for the information.  Are you happy for this issue to be closed now?
