### ISSUE TITLE
kite-http not executable

### ISSUE THREAD

**Issue by AndrGutierrez** [kiteco/vim-plugin#339]
Kite works awesome for me in neovim but everytime I restart my PC I need to open kite, uninstall the plugin, and install it again even if I check Kite automatically starts on boot on my config, I think that it shouldn't be happening

**Comment by airblade** [comment]
That's weird.

When you restart your PC and open neovim:

- does `:filter kite scriptnames` in neovim show anything?
- does `ps -axco command kited` on the command line show anything?

**Comment by cam1l0-g** [comment]
Hi I experienced the same issue, the first time I install the plugin it works. But after reboot the plugin simply doesn't work.
`:filter kite scriptname` shows different file in kite directory. But when I open a python file the autocomplete never shows

**Comment by cam1l0-g** [comment]
> Hi I experienced the same issue, the first time I install the plugin it works. But after reboot the plugin simply doesn't work.
> `:filter kite scriptname` shows different file in kite directory. But when I open a python file the autocomplete never shows

I forgot mention that I am using kite for neovim on a linux machine

**Comment by airblade** [comment]
This sounds like https://github.com/kiteco/vim-plugin/issues/340#issuecomment-762421003.

Please can you check whether `lib/linux/kite-http` in your plugin's directory has execute permissions?

**Comment by cam1l0-g** [comment]
That was the problem. Add exec permission to the file fix it. Thanks!

**Comment by airblade** [comment]
@metalogical This same problem keeps coming up...
