### ISSUE TITLE
Kite not working with Neovim

### ISSUE THREAD

**Issue by e-cal** [kiteco/vim-plugin#340]
I just installed Kite, restarted Neovim, restarted my computer and tried again but still nothing. The plugin is installed and running but completions aren't appearing, Copilot isn't following my cursor, and running `:KiteGotoDefinition` always returns `Kite: unable to find a definition.`

Application Logs: https://s3.console.aws.amazon.com/s3/object/kite-client-logs/prod/646900/kite_local/client.log.2021-01-16_12-14-58-PM.bak.gz

### kite-vim.log 
The triangles are from my fish welcome message I think
```
> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 120ms 'http://127.0.0.1:46624/clientapi/languages'
< △▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽HTTP/1.1 200 OK
< 
< ["bash","c","cpp","csharp","css","go","html","java","javascript","jsx","kotlin","less","objectivec","php","python","ruby","scala","tsx","typescript","vue"]
< 

> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 400ms 'http://127.0.0.1:46624/api/buffer/vim/%3Ahome%3Aecal%3Ascripts%3Atest.py/△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽5aac84a48218316830b58cbc28ee5081/hover?cursor_runes=17'
< HTTP/1.1 404 Not Found
< 
< file not found: /home/ecal/scripts/test.py
< 

> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 400ms 'http://127.0.0.1:46624/api/buffer/vim/%3Ahome%3Aecal%3Ascripts%3Atest.py/△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽5aac84a48218316830b58cbc28ee5081/hover?cursor_runes=17'
< HTTP/1.1 404 Not Found
< 
< file not found: /home/ecal/scripts/test.py
< 

> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 120ms 'http://127.0.0.1:46624/clientapi/languages'
< △▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽HTTP/1.1 200 OK
< 
< ["bash","c","cpp","csharp","css","go","html","java","javascript","jsx","kotlin","less","objectivec","php","python","ruby","scala","tsx","typescript","vue"]
< 

> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 400ms 'http://127.0.0.1:46624/api/buffer/vim/%3Ahome%3Aecal%3Ascripts%3Atest.py/△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽5aac84a48218316830b58cbc28ee5081/hover?cursor_runes=17'
< HTTP/1.1 404 Not Found
< 
< file not found: /home/ecal/scripts/test.py
< 

> /home/ecal/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http --timeout 400ms 'http://127.0.0.1:46624/api/buffer/vim/%3Ahome%3Aecal%3Ascripts%3Atest.py/△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽△▽5aac84a48218316830b58cbc28ee5081/hover?cursor_runes=17'
< HTTP/1.1 404 Not Found
< 
< file not found: /home/ecal/scripts/test.py
< 
```

Kite is running: 
![image](https://user-images.githubusercontent.com/47398876/104818469-e2e20780-57f5-11eb-91aa-2318bb36b74d.png)

And the extension is loaded:
![image](https://user-images.githubusercontent.com/47398876/104818492-fdb47c00-57f5-11eb-9118-ccba364983a5.png)

**Comment by airblade** [comment]
I suspect the triangles are preventing the response being parsed, so nothing works.

Interestingly they are only present for 200 OK responses, not the 404s.

The question is what is triggering those triangles – presumably either the plugin or the `kite-http` helper.

**Comment by airblade** [comment]
The plugin uses `system()` to call out to `kite-http`.  `system()` goes via the shell.

@e-cal Please can you try `:set shell=/usr/local/bin/bash` (or whatever your bash path is) and see if things work?

**Comment by e-cal** [comment]
@airblade That did remove the welcome message from the logs but wasn't the problem. 
But thanks to your suggestion I managed to fix it by adding exec permissions to `~/.config/nvim/pack/kite/start/vim-plugin/lib/linux/kite-http` as it only had read permissions before. I installed everything as per the documentation so I'm not really sure why that was the case but glad I have it working now. Thanks for the help!

**Comment by airblade** [comment]
@e-cal Well spotted!  I'm glad you got it working.

@metalogical This has occurred several times now.  It was supposed to have been fixed in https://github.com/kiteco/kiteco/issues/11177 but evidently the installer doesn't always give `kite-http` execute permissions.
