### ISSUE TITLE
Kite don't show my snippets

### ISSUE THREAD

**Issue by alonso804** [kiteco/vim-plugin#341]
I don't know if there is a way to Kite show my snippets like CoC. I'm using sirver/ultisnips.

**Comment by airblade** [comment]
Kite doesn't have any built-in integration with snippets such as sirver/ultisnips.

The Kite docs talk about snippets; those are Kite's own snippets, i.e. when the completion result is itself a snippet.  But you can't plug in your own snippet source.

**Comment by e-cal** [comment]
@airblade Will using snippets or writing your own to add to kite ever be supported? I noticed even the common basic snippets (such as `if __name__ == "__main__":`) are pro completions which is less than ideal.

**Comment by airblade** [comment]
@metalogical Please could you answer this?

**Comment by metalogical** [comment]
The recommended way to handle this is to try using the [Kite-LSP integration](https://github.com/kiteco/vim-plugin/blob/master/LSP.md), which will integrate Kite completions into your third-party completions provider (which should also be able to integrate with ultisnips, etc). That will be the primary focus for future development.

This is a fairly new integration, so it may be a bit buggy or have some limitations, but I'd recommend trying that. If you notice any bugs or have any requests, please open further issues.
