### ISSUE TITLE
Kite doesn't suggest anything within python-3 f-strings

### ISSUE THREAD

**Issue by terrykong** [kiteco/vim-plugin#350]
Hi team,

Thanks for the great tool!

I'm not sure if this is something the kite vim plugin doesn't support, or is it merely a configuration issue. What I'm observing is Kite doesn't suggest anything if I'm within an f-string context:

![image](https://user-images.githubusercontent.com/7576060/108576861-f7715e00-72d3-11eb-9515-24d8e5d8e7a2.png)

Is there any planned support for this?

Thanks in advance!

**Comment by airblade** [comment]
I can't reproduce this, i.e. Kite does suggest `MY_VARIABLE` to me while I'm typing:

<img width="193" alt="Screenshot 2021-02-23 at 9 52 17 am" src="https://user-images.githubusercontent.com/7265/108826899-d901b000-75bc-11eb-96ad-88befd447ea4.png">

In your screenshot, if you enter insert mode after `MY_` and type ctrl-x ctrl-u, does it work then?

**Comment by terrykong** [comment]
hi @airblade . yea, it strangely works now. i had tried ctrl-x + ctrl-u and even that didn't work. i'll close this issue since i can't reproduce it reliably.
